# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'quick2doo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for quick2doo
  
   pod ‘RxSwift’, :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'rxswift4.0-swift4.0'
   pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'rxswift4.0-swift4.0'
  pod 'RealmSwift'

end
